### Data types

A Pandas DF column is a pd.Series which are internally numpy arrays

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.Series([1, 2, 3]).values

array([1, 2, 3])

### Binary Array arithmetik

Build an array of `True`s and `False`s, one for each row in our dataframe. When we index our dataframe with this array, we get just the rows where our boolean array evaluated to `True`.  It's important to note that for row filtering by a boolean array the length of our dataframe's index must be the same length as the boolean array used for filtering. Binary-array-selection works with any numpy array.

You can also combine more than one condition with the `&` operator

In [3]:
### one dimension

# prepare array of alternating True and False as selector
l=6
select = np.arange(l) % 2 == 0
select

array([ True, False,  True, False,  True, False])

In [4]:
target = np.linspace(10,l*10,l); target

array([10., 20., 30., 40., 50., 60.])

In [5]:
# now select from target 
target[select]

array([10., 30., 50.])

In [6]:
### two dimensions

# prepare some target with l * x dimensions
x = np.array(['a', 'b', 'c'], dtype=object)
target=np.outer(x, np.arange(l))
target = np.transpose(target)
target

array([['', '', ''],
       ['a', 'b', 'c'],
       ['aa', 'bb', 'cc'],
       ['aaa', 'bbb', 'ccc'],
       ['aaaa', 'bbbb', 'cccc'],
       ['aaaaa', 'bbbbb', 'ccccc']], dtype=object)

In [7]:
# now select from 2-dimensional target
target[select]

array([['', '', ''],
       ['aa', 'bb', 'cc'],
       ['aaaa', 'bbbb', 'cccc']], dtype=object)